apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hello-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Simple helm app operator
  displayName: Simple helm app operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - helm
  - simple
  - example
  links:
  - name: Hello Operator
    url: https://hello-operator.domain
  maintainers:
  - email: grahamnscp@gmail.com
    name: grahamsncp
  maturity: alpha
  provider:
    name: grahamnscp
  version: 0.0.0
