apiVersion: hello.grahamh/v1alpha1
kind: Hello
metadata:
  name: hello-sample
spec:
  # Default values copied from <project_dir>/helm-charts/app-chart/values.yaml
  Release:
    Namespace: default
  affinity: {}
  fullnameOverride: ""
  image:
    pullPolicy: IfNotPresent
    repository: grahamh/hello-replicated
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext: {}
  service:
    nodeport: 8082
    port: 8080
    type: NodePort
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  
  
